// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/orders/orders.proto

package mu_micro_book_srv_orders

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	BookId               int64    `protobuf:"varint,2,opt,name=bookId,proto3" json:"bookId,omitempty"`
	OrderId              int64    `protobuf:"varint,3,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e484a55ca159a606, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Request) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *Request) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type Order struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	BookId               int64    `protobuf:"varint,3,opt,name=bookId,proto3" json:"bookId,omitempty"`
	InvHistoryId         int64    `protobuf:"varint,4,opt,name=invHistoryId,proto3" json:"invHistoryId,omitempty"`
	State                int64    `protobuf:"varint,5,opt,name=state,proto3" json:"state,omitempty"`
	CreatedTime          int64    `protobuf:"varint,6,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime          int64    `protobuf:"varint,7,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_e484a55ca159a606, []int{1}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Order) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Order) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *Order) GetInvHistoryId() int64 {
	if m != nil {
		return m.InvHistoryId
	}
	return 0
}

func (m *Order) GetState() int64 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *Order) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *Order) GetUpdatedTime() int64 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Order                *Order   `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e484a55ca159a606, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_e484a55ca159a606, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "mu.micro.book.srv.orders.Request")
	proto.RegisterType((*Order)(nil), "mu.micro.book.srv.orders.Order")
	proto.RegisterType((*Response)(nil), "mu.micro.book.srv.orders.Response")
	proto.RegisterType((*Error)(nil), "mu.micro.book.srv.orders.Error")
}

func init() { proto.RegisterFile("proto/orders/orders.proto", fileDescriptor_e484a55ca159a606) }

var fileDescriptor_e484a55ca159a606 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xcf, 0x4e, 0x32, 0x31,
	0x10, 0xff, 0x96, 0x65, 0x17, 0xbe, 0xc1, 0x78, 0x68, 0x8c, 0xa9, 0x5e, 0xc4, 0x9e, 0x38, 0xd5,
	0x04, 0xe2, 0x23, 0x18, 0xdd, 0x0b, 0x26, 0xc5, 0x17, 0x80, 0xed, 0x1c, 0x1a, 0x85, 0x62, 0xdb,
	0xc5, 0xf8, 0x1a, 0xbe, 0x87, 0x8f, 0xe1, 0x7b, 0x99, 0x4e, 0x17, 0x03, 0x31, 0x70, 0xf2, 0xb4,
	0xfd, 0xfd, 0x99, 0xdf, 0x74, 0x66, 0x0b, 0x17, 0x6b, 0x67, 0x83, 0xbd, 0xb1, 0x4e, 0xa3, 0xf3,
	0xed, 0x47, 0x12, 0xc7, 0xf8, 0xb2, 0x91, 0x4b, 0x53, 0x3b, 0x2b, 0x17, 0xd6, 0x3e, 0x4b, 0xef,
	0x36, 0x32, 0xe9, 0x62, 0x06, 0x3d, 0x85, 0xaf, 0x0d, 0xfa, 0xc0, 0xce, 0xa1, 0x6c, 0x3c, 0xba,
	0x4a, 0xf3, 0x6c, 0x98, 0x8d, 0xba, 0xaa, 0x45, 0x91, 0x8f, 0x55, 0x95, 0xe6, 0x9d, 0x61, 0x36,
	0xca, 0x55, 0x8b, 0x18, 0x87, 0x1e, 0x85, 0x54, 0x9a, 0xe7, 0x24, 0x6c, 0xa1, 0xf8, 0xca, 0xa0,
	0x78, 0x8c, 0x67, 0x76, 0x0a, 0x1d, 0x93, 0xf2, 0x72, 0xd5, 0x31, 0x7a, 0xa7, 0x47, 0x9b, 0xf5,
	0xab, 0x47, 0xbe, 0xd7, 0x43, 0xc0, 0x89, 0x59, 0x6d, 0x1e, 0x8c, 0x0f, 0xd6, 0xbd, 0x57, 0x9a,
	0x77, 0x49, 0xdd, 0xe3, 0xd8, 0x19, 0x14, 0x3e, 0xcc, 0x03, 0xf2, 0x82, 0xc4, 0x04, 0xd8, 0x10,
	0x06, 0xb5, 0xc3, 0x79, 0x40, 0xfd, 0x64, 0x96, 0xc8, 0x4b, 0xd2, 0x76, 0xa9, 0xe8, 0x68, 0xd6,
	0xfa, 0xc7, 0xd1, 0x4b, 0x8e, 0x1d, 0x4a, 0x7c, 0x64, 0xd0, 0x57, 0xe8, 0xd7, 0x76, 0xe5, 0x31,
	0x8e, 0xeb, 0x9b, 0xba, 0x46, 0xef, 0x69, 0x9e, 0xbe, 0xda, 0x42, 0x76, 0x0b, 0x05, 0x3a, 0x67,
	0x1d, 0xcd, 0x34, 0x18, 0x5f, 0xc9, 0x43, 0xdb, 0x96, 0x77, 0xd1, 0xa6, 0x92, 0x3b, 0x96, 0x11,
	0x4d, 0x23, 0x1f, 0x2d, 0xa3, 0x5d, 0xaa, 0xe4, 0x16, 0x13, 0x28, 0x28, 0x86, 0x31, 0xe8, 0xd6,
	0x56, 0x23, 0xdd, 0xa6, 0x50, 0x74, 0x8e, 0x7b, 0xd4, 0x18, 0xe6, 0xe6, 0x85, 0xee, 0xf2, 0x5f,
	0xb5, 0x68, 0xfc, 0x99, 0x41, 0x49, 0x29, 0x9e, 0x4d, 0x21, 0x9f, 0xe2, 0x1b, 0xbb, 0x3e, 0xdc,
	0xae, 0x7d, 0x10, 0x97, 0xe2, 0x98, 0x25, 0x6d, 0x45, 0xfc, 0x63, 0x33, 0xe8, 0xdf, 0x63, 0x48,
	0xbf, 0xfb, 0xaf, 0x42, 0x17, 0x25, 0xbd, 0xdb, 0xc9, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2f,
	0x05, 0x91, 0x5e, 0xd4, 0x02, 0x00, 0x00,
}
